#!/usr/bin/env python

"""
    husarion_controller.py

    purpose: 
    - NODE for main husarion controller
"""

# import relevant libraries
import rospy

# import custom moduels
from husarion_controller.rosbot_mapping import Mapper

def main():
    resolution = rospy.get_param("~map_resolution") # m/cell
    width = rospy.get_param("~width") # cell ==> max_col
    height = rospy.get_param("~height") # cell ==> max_row

    occ_map = Mapper(resolution, width, height)
    

    try:
        occ_map._update_laser_data() 
        occ_map.spin()

    except rospy.ROSInterruptException:
        rospy.logerr("ROS Node interrupted")

if __name__ == "__main__":

    rospy.init_node("mapper")
    
    # Sleep for a few seconds to wait for the registration.
    rospy.sleep(2)
    main()
