#!/usr/bin/env python

"""
    husarion_controller.py

    purpose: 
    - NODE for main husarion controller
"""

# import relevant libraries
import rospy

# import custom moduels
from husarion_controller.rosbot_mapping import Mapper

def main():
    occ_map = Mapper()
    
    try:
        occ_map._update_laser_data()  
        # continuous subscription for laser_scan 
        rospy.spin()

    except rospy.ROSInterruptException:
        rospy.logerr("ROS Node interrupted")

if __name__ == "__main__":

    rospy.init_node("mapper")
    
    # Sleep for a few seconds to wait for the registration.
    rospy.sleep(2)
    main()
